### PR TITLE
Update CronScheduleTest.cpp

### PR DESCRIPTION
**Pull request by nkinar**
Added test for update to Readme: event occurring every minute.

### CODE REVIEW

**Comment by PerMalmberg** [comment]
Why make a separate PR? Just update your branch for this one and push the code to update the PR itself.

The test fails, you're missing the initial timestamp.

**Comment by nkinar** [comment]
@PerMalmberg can you elaborate on what is the initial timestamp that is missing?  Thank you.

Is this

`DT(2018_y / 03 / 1, hours{ 12 }, minutes{ 0 }, seconds{ 0 }) `

Maybe some documentation could be added to the CronScheduleTest.cpp file to indicate how to write an initial timestamp.

**Comment by PerMalmberg** [comment]
@nkinar The first test value needs to be the first calculated schedule, calculated based on the `from` argument (inclusive). In this case, as we're looking at the smallest unit, it has to be the same as the _from_ point itself.

The test also shows what it calculates and expects: https://github.com/PerMalmberg/libcron/actions/runs/10177199677/job/28148138238?pr=38#step:4:8

**Comment by PerMalmberg** [comment]
Test passing, LGTM!

**Comment by nkinar** [comment]
Thanks @PerMalmberg that makes more sense now.  The `from` argument needs to be a time **before** the cron event occurs. The later comparisons are made at the time when the cron event should occur.  All checks have now passed, and I've run the tests locally as well on my machine.

**Pull request merged**
