### PR TITLE
Avoid compiler warnings on compilers supporting std::uncaught_exceptions()

### PR DESCRIPTION
**Pull request by PerMalmberg**

### CODE REVIEW

**Comment by PerMalmberg** [comment]
@HpLightcorner When adding this little fix I noticed the test you added (`Adding 1000 Tasks to two Cron-Objects expiring after 1 second calling add_schedule`) constantly fails. Can you please have a look at it and make a PR?

**Comment by HpLightcorner** [comment]
@PerMalmberg yes, for sure - let me take a look and come back with a PR

**Comment by HpLightcorner** [comment]
@PerMalmberg sorry for being so late with my reply - quite busy times....
I had a look at the Issue and I think we should remove this test as it is indeed depending on the CPU performance of the machine executing the test (which at least shown me that I was able to improve performance during development). What is your opinion?

**Comment by PerMalmberg** [comment]
> @PerMalmberg sorry for being so late with my reply - quite busy times....
> I had a look at the Issue and I think we should remove this test as it is indeed depending on the CPU performance of the machine executing the test (which at least shown me that I was able to improve performance during development). What is your opinion?

I'm OK with that.

**Pull request merged**
